apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlops-engine.fullname" . }}-secrets
  labels:
    {{- include "mlops-engine.labels" . | nindent 4 }}
type: Opaque
data:
  redis-url: {{ .Values.secrets.redisUrl | b64enc | quote }}
  rabbitmq-url: {{ .Values.secrets.rabbitmqUrl | b64enc | quote }}
