apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-candidate-service
  labels:
    app.kubernetes.io/name: {{ include "mlops-engine.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "mlops-engine.name" . }}
    app.kubernetes.io/component: candidate
  ports:
    - name: http
      port: {{ .Values.service.baseline.port }}
      targetPort: {{ .Values.service.baseline.port }}
