apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-worker-service
  labels:
    app.kubernetes.io/name: {{ include "mlops-engine.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "mlops-engine.name" . }}
    app.kubernetes.io/component: worker
  ports:
    - name: webhook
      port: {{ .Values.service.worker.port }}
      targetPort: {{ .Values.service.worker.port }}
    - name: metrics
      port: {{ .Values.service.worker.metricsPort }}
      targetPort: {{ .Values.service.worker.metricsPort }}
